=== nicoduflot/10-XML-3-jours/04-rollodex.dtd
<!ELEMENT rollodex (contact+)>
        <!ELEMENT contact (nom, prenom?, adresses, emails)>
        <!ATTLIST contact personne (physique |morale ) "physique">
        <!ATTLIST contact numero ID #REQUIRED>
            <!ELEMENT nom (#PCDATA)>
            <!ELEMENT prenom (#PCDATA)>
            <!ELEMENT adresses (adresse*)>
                <!ELEMENT adresse (numero, voie, codePostal, ville, pays)>
                    <!ATTLIST adresse type (facturation|livraison) #REQUIRED>
                    <!ATTLIST adresse userAdresse IDREF #REQUIRED>
                    <!ELEMENT numero (#PCDATA)>
                    <!ELEMENT voie (#PCDATA)>
                    <!ATTLIST voie type (rue|avenue|boulevard|impasse|place|route|faubourg) #REQUIRED>
                    <!ELEMENT codePostal (#PCDATA)>
                    <!ELEMENT ville (#PCDATA)>
                    <!ELEMENT pays (#PCDATA)>
            <!ELEMENT emails (email*)>
                <!ELEMENT email (#PCDATA)>
                <!ATTLIST email type (personnel|professionnel) #REQUIRED>

=== nicoduflot/10-XML-3-jours/00-old/04-dtd-externe.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE rollodex SYSTEM "04-rollodex.dtd">
<rollodex>
    <contact personne="physique" numero="n1">
      <!-- Jean Durand, ACME Inc. CEO -->
      <nom>Durand</nom>
      <prenom>Jean</prenom>
      <adresses>
        <adresse type="facturation" userAdresse="n1">
          <numero>7</numero>
          <voie type="impasse">impasse du chemin</voie>
          <codePostal>75015</codePostal>
          <ville>PARIS</ville>
          <pays>FRANCE</pays>
        </adresse>
        <adresse type="livraison" userAdresse="n1">
          <numero>7</numero>
          <voie type="impasse">impasse du chemin</voie>
          <codePostal>75015</codePostal>
          <ville>PARIS</ville>
          <pays>FRANCE</pays>
        </adresse>
        <adresse type="livraison" userAdresse="n1">
          <numero>14</numero>
          <voie type="place">Place des Ã‰tats-Unis</voie>
          <codePostal>75016</codePostal>
          <ville>PARIS</ville>
          <pays>FRANCE</pays>
        </adresse>
      </adresses>
      <emails>
        <email type="personnel">jean.duranc@yahoo.fr</email>
        <email type="professionnel">jdurand@acme.com</email>
      </emails>
    </contact>
    <contact personne="morale" numero="n2">
      <!-- ACME Incorporated main location -->
      <nom>ACME Inc.</nom>
      <adresses>
        <adresse type="facturation" userAdresse="n2">
          <numero>7</numero>
          <voie type="impasse">impasse du chemin</voie>
          <codePostal>75015</codePostal>
          <ville>PARIS</ville>
          <pays>FRANCE</pays>
        </adresse>
        <adresse type="livraison" userAdresse="n2">
          <numero>7</numero>
          <voie type="impasse">impasse du chemin</voie>
          <codePostal>75015</codePostal>
          <ville>PARIS</ville>
          <pays>FRANCE</pays>
        </adresse>
      </adresses>
      <emails>
        <email type="professionnel">contact@acme.com</email>
      </emails>
    </contact>
  </rollodex>
