=== nicoduflot/10-XML-3-jours/00-old/06-banque.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <!-- déclaration des éléments -->
  <xsd:element name="montant" type="xsd:double" />

  <xsd:element name="identite" >
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="nom" type="xsd:string" />
        <xsd:element name="prenom" type="xsd:string" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="compte">
    <xsd:sequence>
      <xsd:element ref="montant" />
    </xsd:sequence>         
  </xsd:complexType>

  <xsd:element name="comptes">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="livretA" type="compte" />
        <xsd:element name="courant" type="compte" />
      </xsd:sequence>
    </xsd:complexType>
   </xsd:element>

  <xsd:element name="client">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="identite" />
        <xsd:element ref="comptes" />
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <!-- Schéma XML -->
  <xsd:element name="banque">
    <xsd:complexType >
      <xsd:sequence>
        <xsd:element ref="client" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>  
  </xsd:element>
</xsd:schema>

=== nicoduflot/10-XML-3-jours/06-banque.xml
<?xml version="1.0" encoding="UTF-8"?>
<banque xsi:noNamespaceSchemaLocation="06-banque.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- 1er client de la banque -->
  <client>
    <!-- identité du client -->
    <identite>
      <nom>NORRIS</nom>
      <prenom>Chuck</prenom>
    </identite>

    <!-- liste des comptes bancaires du client -->
    <comptes>
      <livretA>
        <montant>2500</montant>
      </livretA>
      <courant>
        <montant>4000</montant>
      </courant>
    </comptes>
  </client>
</banque>
